#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_MODULE_LOADER) += module-loader

# list of libraries the app needs to build
# TODO default of hello-3
module-loader-y = common libsel4 libmuslc \
            libsel4muslcsys \
            libsel4simple libsel4vka libsel4allocman libsel4vspace \
            libsel4platsupport \
            libutils libsel4simple-default libsel4utils libsel4debug

module-loader-3: kernel_elf $(module-loader-y)
